#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/concessionaria
#    username: root
#    password: Anno1404!
#
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

token:
  signing:
    #This key is used as base to generate tokens for authentication
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
