spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concessionaria
    username: root
    password: Avenged7x123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update