spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concessionaria
    username: root
    password: Anno1404!

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: test
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
